### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Carreau** [MeeseeksBox/test1#14]
Test for @choldgraf

**Comment by Carreau** [comment]
@meeseeksdev hello

**Comment by Carreau** [comment]
@meeseeksdev help

**Comment by choldgraf** [comment]
omg.

**Comment by choldgraf** [comment]
is it wrong that my initial reaction is to put aside all my work and write a bunch of easter-egg responses for mr meeseeks?

**Comment by Carreau** [comment]
> is it wrong that my initial reaction is to put aside all my work and write a bunch of easter-egg responses for mr meeseeks?

No, feel free to do so.

**Comment by Carreau** [comment]
cc @tacaswell

@meeseeksdev hello

**Comment by tacaswell** [comment]
@meeseeksdev hello

**Comment by tacaswell** [comment]
@meeseeksdev help

**Comment by Carreau** [comment]
@meeseeksdev party

**Comment by Carreau** [comment]
cc @choldgraf 

@meeseeksdev party

**Comment by Carreau** [comment]
Test of collecting metrics:
@meeseeksdev party 
@meeseeksdev party Oweeeee

**Comment by Carreau** [comment]
OOpps bug, retest:

Test of collecting metrics:
@meeseeksdev party
@meeseeksdev say Oweeeee
@meeseeksdev say Can Doooo

**Comment by Carreau** [comment]
Test of collecting metrics one more time
@meeseeksdev party
@meeseeksdev say Oweeeee
@meeseeksdev say Can Doooo
